django_app/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
]

django_app/polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

django_app/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField('질문내용',max_length =200)
    pub_date = models.DateTimeField('발행일자')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)




class Choice(models.Model):
    question = models.ForeignKey(Question, verbose_name ='해당질문', on_delete=models.CASCADE)
    choice_text = models.CharField('선택내용', max_length=200)
    votes = models.IntegerField('총 투표수', default=0)

    def __str__(self):
        return self.choice_text

django_app/polls/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse, Http404

from polls.models import Question, Choice


def index(request):
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # latest_question_list라는 키로 위 쿼리셋을 전달,
    # polls/index.html을 이용해 render한 결과를 리턴

    # get_list_or_404를 사용한 경우
    latest_question_list = get_list_or_404(
        Question.objects.order_by('-pub_date')[:5]
    )

    context = {
        'latest_question_list': latest_question_list,
    }
    # Template Does Not Exist
    # settings.py에서 TEMPLATE_DIR변수 할당 (BASE_DIR와 os.path.join를 사용)
    # TEMPLATE항목의 DIRS 리스트에 위 변수를 추가
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    # question_id가 pk인 Question객체를 가져와
    # context라는 이름을 가진 dict에 'question'이라는 키 값으로 위 변수를 할당
    # 이후 'polls/detail.html'과 context를 렌더한 결과를 리턴

    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist as e:
    #     raise Http404('Question does not exist')

    # question.choice_set.
    # Choice.objects.filter(question=question).

    # get_object_or_404를 사용한 경우
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question,
    }

    # polls/detail에서 해당 question의 question_text를 출력
    return render(request, 'polls/detail.html', context)


def results(request, question_id):
    # detail.html파일을 약간 수정해서 results.html을 만들고
    # 질문에 대한 모든 선택사항의 선택수(votes)를 출력
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question,
    }
    # detail.html내부
    #   question을 출력
    #   해당 question의 모든 choice들 (question.choice_set.all) 출력
    #   loop돌며 각 choice의 제목과 votes를 출력
    return render(request, 'polls/results.html', context)


def vote(request, question_id):
    # request의 method가 POST방식일 때,
    if request.method == 'POST':
        # 전달받은 데이터중 'choice'키에 해당하는 값을
        # HttpResponse에 적절히 돌려준다
        data = request.POST
        try:
            choice_id = data['choice']
            choice = Choice.objects.get(id=choice_id)
            choice.votes += 1
            choice.save()
            return redirect('polls:results', question_id)
        except (KeyError, Choice.DoesNotExist):
            # message프레임워크를 사용
            # 지금 모르셔도 됩니다
            # request에 메시지를 저장해놓고 해당 request에 대한
            # response를 돌려줄 때 메시지를 담아 보낸다
            messages.add_message(
                request,
                messages.ERROR,
                "You didn't select a choice",
            )
            return redirect('polls:detail', question_id)
    else:
        return HttpResponse("You're voting on question %s." % question_id)

django_app/polls/templates/polls/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <title>{% block title %}polls application{% endblock %}</title>
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock %}

</div>

</body>
</html>

django_app/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}

<h1>{{ question.question_text }}</h1>



<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" >
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    {% endfor %}
    <button type="submit">선택</button>
</form>

{% endblock %}

django_app/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
<h1>polls application</h1>
{% if latest_question_list %}

<ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}

</ul>

{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

django_app/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">vote again</a>

{% endblock %}